title: Craigslist Redesign
description: >- # Diese Beschreibung wird für SEO-Zwecke verwendet.
  Das ist eine Beispielbeschreibung für meine Website, die auf GitHub Pages gehostet wird.
url: "https://fotomaexx.github.io" # Die Basis-URL deiner Seite
baseurl: "/Interaktive-Systeme" # Der Basispfad deiner Seite, falls sie in einem Unterverzeichnis gehostet wird

# Build-Einstellungen
markdown: kramdown
theme: minima # Oder ein anderes Theme, falls verwendet
plugins:
  - jekyll-feed

# Exkludierte Dateien und Verzeichnisse
exclude:
  - node_modules/
  - .sass-cache/
  - .jekyll-cache/
  - .nojekyll
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - tailwind.config.js
  - postcss.config.js
  - README.md
  - LICENSE
  - .gitignore
  - .git/

# Optional: Einstellungen für GitHub Pages und SEO
github:
  is_project_page: true # Setze dies auf `true`, wenn deine Seite als Projektseite gehostet wird
seo:
  type: WebPage
  links:
    - rel: canonical
      href: https://fotomaexx.github.io/Interaktive-Systeme
